train_file: ['data/vg_descriptions.json',
  'data/vg_attributes_spatial.json',
  'data/vg_attributes.json']

bert_config: 'configs/config_bert.json'
image_root: 'vg/'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 64
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
phrase_input: True
max_words: 50

add_gcam: True
mask_all: False
mask_size: 256

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 30, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-6, warmup_epochs: 20, cooldown_epochs: 0}






